name: Fibula CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  ACTIONS_STEP_DEBUG: ${{ secrets.ACTIONS_STEP_DEBUG }}

jobs:
  test-native:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Fibula
        uses: actions/checkout@v4
        with:
          path: fibula
      - name: Checkout JMH
        uses: actions/checkout@v4
        with:
          repository: galderz/jmh
          ref: 1.37-jmh-core-it-test-jar
          path: jmh
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: 'dev'
          distribution: 'graalvm-community'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Show versions
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          native-image --version
      - name: Build JMH
        working-directory: jmh
        run: mvn install -DskipTests
      - name: Build Fibula
        working-directory: fibula
        run: mvn install -DskipTests
      # todo make tests really IT to avoid the need to build first?
      - name: Build native runner
        working-directory: fibula
        run: mvn package -DskipTests -pl fibula-it -Pnative
      - name: List jars in native image source jar
        working-directory: fibula
        run: ls -al fibula-it/target/fibula-it-999-SNAPSHOT-native-image-source-jar/lib
      - name: Run integration tests
        working-directory: fibula
        run: mvn test -pl fibula-it

  test-jvm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Fibula
        uses: actions/checkout@v4
        with:
          path: fibula
      - name: Checkout JMH
        uses: actions/checkout@v4
        with:
          repository: galderz/jmh
          ref: 1.37-jmh-core-it-test-jar
          path: jmh
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm-community'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Show versions
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
      - name: Build JMH
        working-directory: jmh
        run: mvn install -DskipTests
      # todo make tests really IT to avoid the need to build first?
      - name: Build Fibula
        working-directory: fibula
        run: mvn install -DskipTests
      - name: Test Fibula
        working-directory: fibula
        run: mvn test -pl fibula-it
