name: Fibula CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  ACTIONS_STEP_DEBUG: ${{ secrets.ACTIONS_STEP_DEBUG }}

jobs:
  test-native:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Fibula
        uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm-community'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Show versions
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          java --version
          native-image --version
      - name: Run integration tests
        run: mvn verify  -pl fibula-it -am

  test-jvm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Fibula
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Show versions
        run: |
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
      - name: Run tests
        run: mvn test  -pl fibula-it -am -Djvm.mode
