name: Fibula CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  jmh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout JMH
        uses: actions/checkout@v4
        with:
          repository: galderz/jmh
          ref: 1.37-jmh-core-it-test-jar
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build JMH
        env:
          JAVA_HOME: ${{ env.JAVA_HOME_21_X64 }}
        run: mvn install -DskipTests
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: jmh-artifacts
          path: |
            ~/.m2/repository/**/jmh*  # adjust path for your specific artifact

  test-native:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: jmh-artifacts
          path: .
      - name: Checkout Fibula
        uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm-community'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Show versions
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          native-image --version
      - name: Build Fibula
        run: mvn install -DskipTests --projects !fibula-it
      - name: Build native runner
        run: mvn package -DskipTests -pl fibula-it -Pnative
      - name: Run integration tests
        run: mvn test -pl fibula-it

  test-jvm:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: jmh-artifacts
          path: .
      - name: Checkout Fibula
        uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm-community'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Show versions
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
      - name: Build Fibula
        run: mvn install -DskipTests --projects !fibula-it
      - name: Build native runner
        run: mvn package -DskipTests -pl fibula-it
      - name: Run integration tests
        run: mvn test -pl fibula-it
