name: Fibula with Quarkus snapshot

on:
  schedule:
    - cron: '5 1 * * 1-5'
  # enable users to manually trigger with workflow_dispatch
  workflow_dispatch:

env:
  COMMON_MAVEN_ARGS: "-e -B -Dquarkus.platform.group-id=io.quarkus -Dquarkus.platform.version=999-SNAPSHOT -Dquarkus-plugin.version=999-SNAPSHOT"

jobs:
  build-quarkus:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Quarkus
        uses: actions/checkout@v4
        with:
          ref: topic.0305.native-jar-building-extra-logging
          repository: galderz/quarkus
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Build Quarkus
        run: |
          ./mvnw -DskipTests -DskipITs -DskipDocs -Dinvoker.skip -Dskip.gradle.tests -Djbang.skip -Dtruststore.skip -Dno-format -Dtcks -Prelocations clean install

  test-native:
    runs-on: ubuntu-latest
    needs: build-quarkus
    steps:
      - name: Checkout Fibula
        uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm-community'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Show versions
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          native-image --version
      - name: Build Fibula
        run: mvn install $COMMON_MAVEN_ARGS -DskipTests --projects !fibula-it
      - name: Build native runner
        run: mvn -X package $COMMON_MAVEN_ARGS -DskipTests -pl fibula-it -Prunner-native
      - name: Run integration tests
        run: mvn test $COMMON_MAVEN_ARGS -pl fibula-it
