name: Fibula Samples

on:
  schedule:
    - cron: '5 1 * * 1-5'
  # enable users to manually trigger with workflow_dispatch
  workflow_dispatch:
    inputs:
      quick:
        description: 'Run samples quickly'
        required: true
        default: 'false'

jobs:
  run:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Fibula
        uses: actions/checkout@v4
        with:
          path: fibula
      - name: Checkout JMH
        uses: actions/checkout@v4
        with:
          repository: openjdk/jmh
          path: jmh
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm-community'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Show versions
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          echo "JAVA_HOME_21_X64: $JAVA_HOME_21_X64"
          java --version
          native-image --version
      - name: Build JMH
        working-directory: jmh
        env:
          JAVA_HOME: ${{ env.JAVA_HOME_21_X64 }}
        run: mvn install -DskipTests
      - name: Build Fibula
        working-directory: fibula
        run: mvn install -DskipTests
      - name: Build native runner
        working-directory: fibula
        run: mvn -X package -DskipTests -pl fibula-samples -Prunner-native
      - name: Run integration tests
        working-directory: fibula
        env:
          JAVA_HOME: ${{ env.JAVA_HOME_21_X64 }}
        run: mvn test -pl fibula-samples -Dfibula.test.quick=${{ github.event.inputs.quick }}
